Draft: open_dataset improvements
C2SM/iconarray pull request #55
Opened 2023-02-27 14:07 UTC by victoria-cherkas

2023-02-27 18:04 UTC, victoria-cherkas commented
launch jenkins

2023-02-28 08:25 UTC, victoria-cherkas commented
launch jenkins

2023-02-28 09:46 UTC, victoria-cherkas commented
launch jenkins

2023-02-28 15:52 UTC, victoria-cherkas commented
for this file `grib= '/scratch/vcherkas/iconarray/data/example_data/grib/lfff00010000_edgeplots'`:

Elapsed time GRIB (unfiltered): `ds = iconarray.open_dataset(grib)`
New `open_dataset()`: 0:02:13
Old `open_dataset()`: 0:02:39

So not to worry about performance loss, it is clearly just a large file (that should probably have been cropped before uploading to the example data server).

2023-02-28 16:03 UTC, victoria-cherkas commented
> Great! I think we should make it a task to reduce the test data size. We can for example crop the data to a smaller domain

https://github.com/C2SM/iconarray/issues/57 Just added issue for it :)

2023-03-01 10:12 UTC, clairemerker requested changes
I made a little comment, but I really like it! I will try to implement a little test for the "variable not found" case, so maybe we can wait for this test before we merge.

2023-03-01 10:33 UTC, victoria-cherkas commented on iconarray/backend/grid.py
> +    backend_kwargs=None,
This is what I had originally but I changed it because I had a pre-commit warning related to using mutable objects as default argument in Python: eg. https://medium.com/geekculture/do-not-use-objects-as-default-arguments-in-python-1c940212db2e

2023-03-01 10:39 UTC, victoria-cherkas commented
Ok thanks for the review @clairemerker we can wait for additional test, thanks for that

2023-03-01 10:45 UTC, clairemerker commented on iconarray/backend/grid.py
> +    backend_kwargs=None,
Haha ok, the linters of course always win! :D

2023-03-01 15:08 UTC, clairemerker commented
launch jenkins

2023-03-01 15:10 UTC, clairemerker approved these changes

2023-03-02 14:38 UTC, clairemerker commented
launch jenkins

2023-03-02 14:39 UTC, clairemerker commented
@victoria-cherkas did you already test this PR with icon-vis?

2023-03-06 10:44 UTC, victoria-cherkas commented
> @victoria-cherkas did you already test this PR with icon-vis?

Yes its passing on icon-vis :)

2023-03-06 10:48 UTC, merged