Implement ind_from_latlon using a cKDTree
C2SM/iconarray pull request #59
Opened 2023-03-23 16:48 UTC by leuty

I tried using ind_from_latlon on with the new ICON-1 domain of MCH and it was kinda slow (20 Min). I implemented a new version using a K-D tree.

I also added functionality to return the n closest points. That is super useful if one want to compare against instruments and avoid double penalties by slight location offsets.

2023-03-23 16:54 UTC, leuty commented
Note, an version for spherical earth can be found here:

https://github.com/Unidata/python-workshop/blob/fall-2016/notebooks/netcdf-by-coordinates.ipynb

2023-05-12 07:39 UTC, AnnikaLau commented
Thanks for the update/improvement! I'm still going through it but one thing I'm not sure of yet, would `ind[0]` be the closest of the closest points?

2023-05-15 08:37 UTC, leuty commented
@AnnikaLau 
 I think the distinction is made by either passing `k=n`  or `k=[n]` to `cKDTree.query`, see [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.query.html).

Would it help if I re-implemented the `verbose` option for `ind_from_latlon` ?

2023-05-15 12:32 UTC, AnnikaLau commented
> @AnnikaLau I think the distinction is made by either passing `k=n` or `k=[n]` to `cKDTree.query`, see [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.query.html).
> 
> Would it help if I re-implemented the `verbose` option for `ind_from_latlon` ? Then you can test.

Yes I think the `verbose` option is useful for the case k=1, which we use for the icon-vis examples. So that the users are aware of that the location of the nearest point might be quite different. So it would be great if you could re-implement it for that case.

2023-05-16 06:49 UTC, leuty commented
@AnnikaLau 
`So that the users are aware of that the location of the nearest point might be quite different.`

I dont understand. Does it yield a different location for your case?

2023-05-16 12:56 UTC, AnnikaLau requested changes

2023-05-16 12:56 UTC, AnnikaLau commented on iconarray/core/utilities.py
> +        print(f"Given lon: {lon_point} vs {n} closest lons found: {closest_lons}")
This sounds a bit confusing when n=1. Should we change it to something like:
print(f"Given lat: {lat_point}. Closest {n} lat/s found: {closest_lats}")

2023-05-16 12:59 UTC, leuty commented on iconarray/core/utilities.py
> +    ds : xarray.Dataset
On top of the file `import xarray` not `import xarray as xr`. I did it consistently. Should I change it everywhere, including the import?

2023-05-16 13:02 UTC, AnnikaLau commented on iconarray/core/utilities.py
> +    ds : xarray.Dataset
Yes, I would change it everywhere in the script. I think that's standard Python style. At least we did it in other scripts, so let's be consistent.

2023-05-16 13:03 UTC, leuty commented on iconarray/core/utilities.py
> +        print(f"Given lon: {lon_point} vs {n} closest lons found: {closest_lons}")
fixed

2023-05-16 13:05 UTC, AnnikaLau commented on iconarray/core/utilities.py
> +        print(f"Given lat: {lon_point}. Closest {n} lat/s found: {closest_lons}")
```suggestion
        print(f"Given lon: {lon_point}. Closest {n} lon/s found: {closest_lons}")
```

2023-05-16 13:06 UTC, leuty commented on iconarray/core/utilities.py
> +    ds : xarray.Dataset
done

2023-05-16 13:42 UTC, AnnikaLau commented
I created a corresponding merge request for icon-vis: https://github.com/C2SM/icon-vis/pull/39

2023-05-31 08:02 UTC, leuty commented on iconarray/core/utilities.py
> -    Examples
Done

2023-05-31 10:22 UTC, AnnikaLau commented on iconarray/core/utilities.py
>      >>> lons = np.rad2deg(ds.clon.values[:])
```suggestion
    >>> lats = xr.DataArray(np.rad2deg(data.clat), coords=data.clat.coords, dims=data.clat.dims)
    >>> lons = xr.DataArray(np.rad2deg(data.clon), coords=data.clon.coords, dims=data.clon.dims)
```

2023-05-31 12:22 UTC, AnnikaLau commented on iconarray/core/utilities.py
>      >>> lons = np.rad2deg(ds.clon.values[:])
The old version doesn't work anymore with the changes to the script.

2023-05-31 15:40 UTC, leuty commented on iconarray/core/utilities.py
>      >>> lons = np.rad2deg(ds.clon.values[:])
I dont understand why exactly, but fine with me.

2023-05-31 15:42 UTC, leuty commented
@AnnikaLau 
I realized that my approach did not work with global domains. I now use another Tree Data Structure and Haversines to compute the distances. The downside is that it adds another dependency: skikit-learn.

2023-06-01 13:05 UTC, AnnikaLau commented on iconarray/core/utilities.py
> +def ind_from_latlon(
If the input order is changed from lat-lon to lon-lat, the name of the function should also be adapted but I think the lat-lon order makes more sense

2023-06-08 16:39 UTC, leuty commented on iconarray/core/utilities.py
> +    n : int, optional
this should be fixed now

2023-06-08 16:40 UTC, leuty commented on iconarray/core/utilities.py
>      >>> lons = np.rad2deg(ds.clon.values[:])
This is now simplified

2023-06-09 07:50 UTC, AnnikaLau commented on iconarray/core/utilities.py
> +    >>> lons = ds.clon
```suggestion
    >>> lats = ds.clat
    >>> lons = ds.clon
    >>> if ds.clat.attrs.get('units') == 'radian':
    >>>     lats = np.rad2deg(lats)
    >>>     lons = np.rad2deg(lons)
```

2023-06-13 09:48 UTC, leuty commented on iconarray/core/utilities.py
> +    >>> lons = ds.clon
This is now done with the last commit, correct?

2023-06-13 09:50 UTC, AnnikaLau commented on iconarray/core/utilities.py
> +    >>> lons = ds.clon
yes

2023-06-13 11:59 UTC, AnnikaLau approved these changes
Waiting for approval of https://github.com/C2SM/icon-vis/pull/39

2023-06-13 14:44 UTC, victoria-cherkas approved these changes

2023-06-13 14:46 UTC, merged